name: Run dbt models

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
    # dbt env variables used in your dbt profiles.yml
    DBT_PROFILES_DIR: ./
    DBT_GOOGLE_PROJECT: ${{ vars.DBT_GOOGLE_PROJECT }}
    DBT_GOOGLE_DATASET: ${{ vars.DBT_GOOGLE_DATASET }}
    DBT_GOOGLE_KEYFILE: /tmp/google/google-service-account.json

    # the contents of the keyfile pulled from GitHub Actions secrets 
    KEYFILE_CONTENTS: ${{secrets.KEYFILE_CONTENTS}}

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
        
        # prep Google keyfile
      - run: mkdir -p "$(dirname $DBT_GOOGLE_KEYFILE)"  
      - run: echo "$KEYFILE_CONTENTS" > $DBT_GOOGLE_KEYFILE

        # checkout the repository content
      - name: checkout repo content
        uses: actions/checkout@v4 
        
        # setup python
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' 

        # install dbt
      - name: install dbt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          dbt deps
          dbt --version
          dbt debug --connection

        # run dbt
      - name: run dbt models
        run: |
            dbt run --profile dbt-prod
            dbt test --profile dbt-prod