name: Run dbt models

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
    TMP_GCP_KEYFILE: /tmp/google/google-service-account.json
    GCP_SERVICE_ACCOUNT_KEYFILE: ${{ secrets.GCP_SERVICE_ACCOUNT_KEYFILE }}

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
        
        # prep Google keyfile
      - run: mkdir -p "$(dirname $TMP_GCP_KEYFILE)" 
      - run: echo "$GCP_SERVICE_ACCOUNT_KEYFILE" > $TMP_GCP_KEYFILE

        # checkout the repository content
      - name: checkout repo content
        uses: actions/checkout@v4 
        
        # setup python
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' 

        # install dbt
      - name: install dbt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          dbt deps
          dbt --version
          dbt debug --connection

        # run dbt
      - name: run dbt models
        run: |
            dbt run
            dbt test